{
 "title": "App Metrics - Web Monitoring - Prometheus",
 "description": "Dashboard to visualize metrics captured by App Metrics ASP.NET Core Middleware 1.2.0, tested with App.Metrics.Formatters.Prometheus 1.1.0  - http://app-metrics.io/",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "query": { "query": "label_values(env)" } },
   { "name": "application", "query": { "query": "label_values(app)" } },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_httprequests_one_minute_error_percentage_rate{env=\"$environment\",app=\"$application\"}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "query": "SELECT  \"value\" FROM \"application.httprequests__percentage_error_requests\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_httprequests_active{env=\"$environment\",app=\"$application\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "apdex" }
   ],
   "targets": [
    {
     "expr": "application_httprequests_apdex{env=\"$environment\",app=\"$application\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1 min rate",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\"}[5m])*60",
     "legendFormat": "5 min rate"
    },
    {
     "expr": "rate(application_httprequests_transactions_count{env=\"$environment\",app=\"$application\"}[15m])*60",
     "legendFormat": "15 min rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",quantile=\"0.75\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",quantile=\"0.95\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "application_httprequests_transactions{env=\"$environment\",app=\"$application\",quantile=\"0.99\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "application_httprequests_one_minute_error_percentage_rate{env=\"$environment\",app=\"$application\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_http_status_code",
     "expr": "application_httprequests_errors{env=\"$environment\",app=\"$application\"}",
     "groupBy": [
      { "params": [ "http_status_code" ], "type": "tag" }
     ],
     "legendFormat": "{{http_status_code}}",
     "measurement": "application.httprequests__errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "rate(application_httprequests_error_rate_total[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1min rate",
     "measurement": "application.httprequests__error_rate",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "rate(application_httprequests_error_rate_total[5m])*60",
     "legendFormat": "5min rate"
    },
    {
     "expr": "rate(application_httprequests_error_rate_total[15m])*60",
     "legendFormat": "15min rate"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "rate(application_httprequests_transactions_per_endpoint_count{env=\"$environment\",app=\"$application\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time / Endpoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "application_httprequests_transactions_per_endpoint{env=\"$environment\",app=\"$application\",quantile=\"0.95\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times / Endpoint",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "application_httprequests_transactions_per_endpoint{env=\"$environment\",app=\"$application\",quantile=\"0.95\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Request Percentage / Endpoint",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "application_httprequests_one_minute_error_percentage_rate_per_endpoint{env=\"$environment\",app=\"$application\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate_per_endpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "rate(application_httprequests_transactions_per_endpoint_count{env=\"$environment\",app=\"$application\"}[1m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{route}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  { "title": "PUT & POST Request Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Post Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "application_httprequests_post_size{env=\"$environment\",app=\"$application\",quantile=\"0.75\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__post_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "application_httprequests_post_size{env=\"$environment\",app=\"$application\",quantile=\"0.95\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "application_httprequests_post_size{env=\"$environment\",app=\"$application\",quantile=\"0.99\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Put Request Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "application_httprequests_put_size{env=\"$environment\",app=\"$application\",quantile=\"0.75\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__put_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    },
    {
     "expr": "application_httprequests_put_size{env=\"$environment\",app=\"$application\",quantile=\"0.95\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "application_httprequests_put_size{env=\"$environment\",app=\"$application\",quantile=\"0.99\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  }
 ]
}